- protoletariat/rewrite.py
- refactor: generalize return type
- refactor: clean up indexing
> small refactor

- .github/workflows/docker.yml
- README.md
- docs: add status badges for CI and PyPI
- ci: add ghcr docker image setup
> ci: add badges and add docker publishing step to GHCR

- protoletariat/fdsetgen.py
- protoletariat/rewrite.py
- protoletariat/tests/test_rewrite.py
> fix: fix nested imports

- flake.nix
- poetry-overrides.nix
- poetry.lock
- protoletariat/fdsetgen.py
- protoletariat/rewrite.py
- protoletariat/tests/conftest.py
- protoletariat/tests/test_rewrite.py
- pyproject.toml
- build: fix pydocstyle search dir
- chore: add dependencies to have a better round trip
- fix: use ast replacement everywhere because typed_ast/typed_astunparse performs correct roundtrip
> fix idempotency

- poetry-overrides.nix
- perf: use cpp implementation for python protobuf
- refactor: pull flit-core from self not super
- style: rename super -> pysuper
- style: rename self -> pyself
> perf: cpp proto

- .github/workflows/ci.yml
- protoletariat/__main__.py
- protoletariat/fdsetgen.py
- protoletariat/tests/conftest.py
- protoletariat/tests/test_buf.py
> fix: ignore google/protobuf by default, allow ignorance of glob patterns

- protoletariat/fdsetgen.py
- refactor: remove use of re in favor of Path
- perf: only iterate through files and dependencies once
> perf: iterate through files and dependencies once

- README.md
- protoletariat/__main__.py
- protoletariat/fdsetgen.py
- protoletariat/tests/conftest.py
> feat: add the ability to bring your own (FileDescriptorSet) bytes

- poetry.lock
- protoletariat/fdsetgen.py
- pyproject.toml
- perf: remove the use of a dict to store rewriters
- style: rename to reflect specific usage
> perf: don't store a dict entry per fd

- .github/workflows/ci.yml
- flake.nix
- build: set exePath to the right thing
- test: start testing tensorflow because it has a large number of protobufs
> test(ci): add tensorflow rewriting check in ci

- .github/workflows/ci.yml
- poetry.lock
- protoletariat/__main__.py
- protoletariat/fdsetgen.py
- pyproject.toml
- test: add doctests
- chore: remove bogus dump
- feat: support click 7
> feat: support earlier click version

- .github/renovate.json
- .github/workflows/ci.yml
- flake.nix
- protoletariat/tests/test_fix_imports.py
- ci: trim the renovate config
- ci: test Python 3.10 with nix in CI
> ci: test Python 3.10 with nix in CI

- flake.lock
- flake.nix
- perf: build docker image with musl
- build: remove even more unused modules
- build: reduce everything up to but not including musl
> perf: reduce everything up to but not including musl

- .github/workflows/ci.yml
- flake.nix
- poetry-overrides.nix
~Depends on https://github.com/nix-community/poetry2nix/pull/466~
> perf: build docker image with musl

- protoletariat/__main__.py
- protoletariat/fdsetgen.py
- protoletariat/tests/conftest.py
> feat(buf): forward input argument to command

- .releaserc.json
- ci/release/dry_run.sh
- ci/release/run.sh
- ci: use conventional commits for release notes style
- chore: add in proper node package dependency
> ci: conventional commits

- protoletariat/fdsetgen.py
- protoletariat/tests/conftest.py
> fix: support proto file names containing hyphens

- protoletariat/fdsetgen.py
- protoletariat/rewrite.py
- protoletariat/tests/test_fix_imports.py
> fix(codegen): don't traverse or generate code with `__pycache__` and dedup generated imports

- flake.lock
- poetry-overrides.nix
- poetry.lock
- chore(deps): bump nixpkgs
- chore: add `grpc-stubs` override and remove unnecessary overrides
> bump nixpkgs

- protoletariat/fdsetgen.py
- protoletariat/rewrite.py
- protoletariat/tests/conftest.py
- protoletariat/tests/test_fix_imports.py
> fix: rewrite `import public` imports in generated code

- .github/workflows/ci.yml
- poetry.lock
- protoletariat/fdsetgen.py
- protoletariat/tests/conftest.py
- pyproject.toml
> feat(protoc): support using `grpc_tools.protoc`

- ci/release/dry_run.sh
- ci/release/run.sh
> ci: try unpinning semrel deps

- .github/workflows/ci.yml
- .github/workflows/update-deps.yml
- flake.lock
Bump flakes and update version in update-deps workflow
> chore(deps): bump flakes and update version in update-deps workflow
