cpcloud/protoletariat

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

- ci: run codeql against the correct branch name
- ci: wire up the docker image in CI

wire up docker image

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`dbabce36`](https://github.com/NixOS/nixpkgs/commit/dbabce365c0d273ac7541b96533313b43280b2a1) | `python3.pkgs.holoviews: remove optional dependencies`                          |
| [`b8173c4a`](https://github.com/NixOS/nixpkgs/commit/b8173c4a0e03f3f25601bf4c12175a9fa6a887f0) | `luaPackages.moonscript: Correct package version to dev-1`                      |
| [`e9f11956`](https://github.com/NixOS/nixpkgs/commit/e9f119566ad0437cc9538 …

chore(flake/nixpkgs): `d00918cc` -> `db223258`

---

flake.lock

| SHA256                                                                                                       | Commit Message            |
| ------------------------------------------------------------------------------------------------------------ | ------------------------- |
| [`dd3e1586`](https://github.com/cachix/pre-commit-hooks.nix/commit/dd3e1586243bbd4f0bdf1df1284d22c9b298e72a) | `Support per-hook stages` |

chore(flake/pre-commit-hooks): `50cfce93` -> `c3b4f943`

---

.github/workflows/ci.yml
.prettierignore
README.md
flake.nix
poetry.lock
protoletariat/__main__.py
protoletariat/fdsetgen.py
protoletariat/rewrite.py
protoletariat/tests/test_rewrite.py
pyproject.toml

- chore: tell prettier to ignore pytest's cache
- build: add types-protobuf to dev deps
- chore: add mypy to pre-commit checks
- chore(dev-deps): add buf to devShell
- refactor: add type annotation to matches function
- style: normalize strings
- test: add buf test
- test: factor out common "out" path check
- fix: remove warning from collections usage
- feat(cli): add support for generating FileDescriptorSet blobs using `buf`

feat: support buf for FileDescriptorSet generation

---

flake.lock

| [`5dadb771`](https://github.com/NixOS/nixpkgs/commit/5dadb7717f34c2fb95bedc22cf279ef9eb095983) | `python3Packages.datatable: fix for non-x86`                              |
| [`cee6c6ca`](https://github.com/NixOS/nixpkgs/commit/cee6c6ca4e65fa0c5931968bd03e404ba3436072) | `azure-cli: remove PEP420 patching to azure packages`                     |
| [`8d96e200`](https://github.com/NixOS/nixpkgs/commit/8d96e200dde3083c412d09f8d9bd6abf4116d141) | …

chore(flake/nixpkgs): `db223258` -> `5dadb771`

---

flake.lock

| SHA256                                                                                                    | Commit Message            |
| --------------------------------------------------------------------------------------------------------- | ------------------------- |
| [`27b4c678`](https://github.com/nix-community/poetry2nix/commit/27b4c6784286a1ee0ca7571126d2d9eaa3878a2b) | `overrides: add kerberos` |

chore(flake/poetry2nix): `b23b074f` -> `ac1b5659`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                         |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`c691e088`](https://github.com/NixOS/nixpkgs/commit/c691e088d79dc154b15568b6dbaece1c1aa473e3) | `bazel_4: Fix Bazel-built protoc segfault on macOS Monterey (#147097)` |
| [`86c48e88`](https://github.com/NixOS/nixpkgs/commit/86c48e88b08e976f258775394a1901d33a66968a) | `nim_builder: do not use output* env variables`                        |
| [`4a22fd0d`](https://github.com/NixOS/nixpkgs/commit/4a22fd0d8fb38f7bfd804a52b2ddccfc8ba958ee) | …

chore(flake/nixpkgs): `5dadb771` -> `4f326207`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                               |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`1eeffcbc`](https://github.com/NixOS/nixpkgs/commit/1eeffcbc01300669c87d5e648af14fbe7eb633f1) | `ArchiSteamFarm: fix build`                                                  |
| [`a988b71a`](https://github.com/NixOS/nixpkgs/commit/a988b71a096dae615358d60d95ca02c1da454d97) | `plasma-hud: init at 19.10.1 (#74085)`                                       |
| [`31b46dd7`](https://github.com/NixOS/nixpkgs/commit/31b46dd7f9af9c4360c5796a885c8ec7e …

chore(flake/nixpkgs): `4f326207` -> `38116953`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                               |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| [`4b5c3d93`](https://github.com/NixOS/nixpkgs/commit/4b5c3d9376a829f454d195d0c8053a160f6b4fbe) | `qemu: only include alsa-lib for alsa support`                               |
| [`5d9e0f86`](https://github.com/NixOS/nixpkgs/commit/5d9e0f86b9883ab309acaa6607a9dc0e7372ad2b) | `qemu: never use bundled Meson`                                              |
| [`0b12f0c1`](https://github.com/NixOS/nixpkgs/commit/0b12f0c1c93664bcf82a95e4746446cbf …

chore(flake/nixpkgs): `38116953` -> `07e3b292`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                       |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- |
| [`92c01996`](https://github.com/NixOS/nixpkgs/commit/92c0199687e1838710571020bf7f6957dc7629e1) | `iterm2: 3.4.0 -> 3.4.13`                                            |
| [`9949f100`](https://github.com/NixOS/nixpkgs/commit/9949f1009d9ce7c58d94cf69b4de3bd58087cf98) | `pantheon.switchboard-plug-onlineaccounts: 6.2.1 -> 6.2.2`           |
| [`129a6094`](https://github.com/NixOS/nixpkgs/commit/129a60944321ce8754e3d191f7641aae4e237896) | …

chore(flake/nixpkgs): `07e3b292` -> `27abb57b`

---

flake.lock

| SHA256                                                                                                    | Commit Message                                                |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| [`62b1ec8c`](https://github.com/nix-community/poetry2nix/commit/62b1ec8cc9ab9e6be1c8cdb7994f2402bb932309) | `Update attribution and copyright to reflect Tweag's support` |

chore(flake/poetry2nix): `ac1b5659` -> `36c215f7`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                     |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`621f57ba`](https://github.com/NixOS/nixpkgs/commit/621f57ba6fa1efbb1785430c5919235ed67d3972) | `skopeo: 1.5.1 -> 1.5.2`                                           |
| [`f5b1b869`](https://github.com/NixOS/nixpkgs/commit/f5b1b86934eaf00d8a10646e7fd6d3a00de2c8d5) | `python3Packages.netdata: 0.2.1 -> 1.0.1`                          |
| [`c254a6e1`](https://github.com/NixOS/nixpkgs/commit/c254a6e12e2c82efaa03b890ec90e5b8ec009d71) | `factor98: add …

chore(flake/nixpkgs): `27abb57b` -> `fc9ee3bc`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                   |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| [`f104c143`](https://github.com/NixOS/nixpkgs/commit/f104c1434bb9458da9b49c0c9a7066c8e3d967c3) | `tinyscheme: add aarch64-darwin to badplatforms`                 |
| [`70307e16`](https://github.com/NixOS/nixpkgs/commit/70307e16745959c52fc6889ae546f1e4887e16ee) | `lima: 0.7.3 -> 0.7.4`                                           |
| [`8959f7b2`](https://github.com/NixOS/nixpkgs/commit/8959f7b2110972fce5f5025517399f7297dad040) | `python3Packages.flake8-polyfill: …

chore(flake/nixpkgs): `fc9ee3bc` -> `d920e9a8`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                             |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ |
| [`dcb941f3`](https://github.com/NixOS/nixpkgs/commit/dcb941f3ede938c01b82ea6be4aa148eb479a413) | `security/pam: Document test location`                                                     |
| [`3b2e6e72`](https://github.com/NixOS/nixpkgs/commit/3b2e6e72faff6255230b17991eb545824b00630f) | `tests: Move all PAM tests into a separate directory`                                      |
| …

chore(flake/nixpkgs): `d920e9a8` -> `16eb0035`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                                |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| [`b3572654`](https://github.com/NixOS/nixpkgs/commit/b35726542e8cf68512e87fbd23eb22778f977f22) | `docbookrx: fix build`                                                                        |
| [`8d4f2c38`](https://github.com/NixOS/nixpkgs/commit/8d4f2c38168d8822584c255a4cccb5946aa85205) | `streamlink: 3.0.1 -> 3.0.3`                                                                  |
| …

chore(flake/nixpkgs): `16eb0035` -> `3e610e1d`

---

flake.lock

| SHA256                                                                                               | Commit Message                                                                |
| ---------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`74f7e431`](https://github.com/numtide/flake-utils/commit/74f7e4319258e287b0f9cb95426c9853b282730b) | `eachSystem: push down `system` as far down as possible for Hydra jobs (#46)` |
| [`ad1f7522`](https://github.com/numtide/flake-utils/commit/ad1f7522aa667e91471d8335d519fc2e2e2856e8) | `Bump cachix/install-nix-action from 15 to 16 (#49)`                          |

chore(flake/flake-utils): `bba5dcc8` -> `74f7e431`

---

flake.lock

| [`37af67a8`](https://github.com/NixOS/nixpkgs/commit/37af67a84a6210c65ce7e61efcad9bf96e3dbc50) | `rdma-core: 37.1 -> 38.0`                                                 |
| [`5c589d83`](https://github.com/NixOS/nixpkgs/commit/5c589d83edadc493b0c99a663f1433cf9c8f2b80) | `libretro: fix core platforms`                                            |
| [`7ff536ed`](https://github.com/NixOS/nixpkgs/commit/7ff536edd6a8fff222889229dce7d2673f0ab463) | …

chore(flake/nixpkgs): `3e610e1d` -> `fb41277d`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`2d4606a3`](https://github.com/NixOS/nixpkgs/commit/2d4606a32d27b5c1429574dc72487490206b5aa8) | `qt4: pull upstream fix for gcc-11 (#147555)`                                       |
| [`ee1f1e0e`](https://github.com/NixOS/nixpkgs/commit/ee1f1e0e4ee17729b312f96e91f47ada20b9f36e) | `dbeaver: 21.2.5 -> 21.3.0`                                                         |
| …

chore(flake/nixpkgs): `fb41277d` -> `089cfc88`

---

flake.lock

| SHA256                                                                                                    | Commit Message                                   |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| [`42b1e673`](https://github.com/nix-community/poetry2nix/commit/42b1e673aa5a9c9236a86ae93d100ddcaf997108) | `Include the trailing slash in legacy index URL` |

chore(flake/poetry2nix): `36c215f7` -> `41732777`

---

flake.lock

| [`11313ae4`](https://github.com/NixOS/nixpkgs/commit/11313ae4112f884e5d70bc342d361726c69cf3e2) | `nwjs: 0.33.4 -> 0.54.1`                                                  |
| [`8ecf2d61`](https://github.com/NixOS/nixpkgs/commit/8ecf2d613aa3cf56821604df894dc2b90f4b128b) | `symfony-cli: support more platforms (#147732)`                           |
| [`dbd39c4d`](https://github.com/NixOS/nixpkgs/commit/dbd39c4d41fb8ef843e1a621dfa47c30e58a3061) | …

chore(flake/nixpkgs): `089cfc88` -> `33ef578c`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                          |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`9d3d02f9`](https://github.com/NixOS/nixpkgs/commit/9d3d02f9c1272f1845bcd3295a22f4a3acb6326a) | `screen: disable parallel build (#147990)`                                              |
| [`0a989ec7`](https://github.com/NixOS/nixpkgs/commit/0a989ec7caa63aabd47b4aff5aecd5a754cd6cea) | `pantheon.elementary-files: drop filechooser-portal-hardcode-gsettings-for-nixos.patch` |
| …

chore(flake/nixpkgs): `33ef578c` -> `7b031d0d`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| [`1923c51c`](https://github.com/NixOS/nixpkgs/commit/1923c51c0ae99671ba5af07c25c77996fd46a49a) | `cdesktopenv: fix build on upcoming binutils-2.36 (#146750)`                  |
| [`efd9bd36`](https://github.com/NixOS/nixpkgs/commit/efd9bd36672e8115eeb7011c0e1fb56bb6622031) | `lifeograph: init at 2.0.2`                                                   |
| [`1b6daffd`](https://github.com/NixOS/nixpkgs/commit/1b6daffd8494af0ed1504370cb7f5 …

chore(flake/nixpkgs): `7b031d0d` -> `c1ab62e7`

---

protoletariat/fdsetgen.py
protoletariat/rewrite.py

- refactor: remove typed-ast usage
- refactor: remove use of re in favor of Path
- refactor: add and correct docstrings and add type aliases for readability

refactor: add and correct docstrings and add type aliases for readability

---

flake.lock

| SHA256                                                                                         | Commit Message                                                          |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- |
| [`7a66744a`](https://github.com/NixOS/nixpkgs/commit/7a66744a78547843bb05bd2c75ad5e537544979d) | `.github/labeler.yml: tag neovim files with "vim" label`                |
| [`137a1536`](https://github.com/NixOS/nixpkgs/commit/137a15365503782e44f33772e4562b7eb222765f) | `neovim: provide default value for python3Env (#147241)`                |
| [`fc48d182`](https://github.com/NixOS/nixpkgs/commit/fc48d182bc6e58e8c4c210a7e142c3b1c67c8d1c) | `neovim: …

chore(flake/nixpkgs): `c1ab62e7` -> `0943a5c5`

---

flake.lock

| [`1195e8ce`](https://github.com/NixOS/nixpkgs/commit/1195e8cecc8651d7168e4064a4d4c4e6e83a985a) | `clj-kondo: 2021.10.19 -> 2021.12.01`                                     |
| [`a542c7c8`](https://github.com/NixOS/nixpkgs/commit/a542c7c8c52b1d7ba014c326126cd298f8e0720e) | `esphome: apply patch to fix subprocess usage`                            |
| [`f69af24c`](https://github.com/NixOS/nixpkgs/commit/f69af24c74715039420a999690870433ef991127) | …

chore(flake/nixpkgs): `0943a5c5` -> `a77874bb`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                    |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [`cf6fc1fd`](https://github.com/NixOS/nixpkgs/commit/cf6fc1fd1734373a5dc9dc6c223caaaad2a8592e) | `podman-compose: 2021-05-18 → 0.1.8`                              |
| [`559edc03`](https://github.com/NixOS/nixpkgs/commit/559edc03590da7bf77bfa262a111cf0834473aa7) | `bunnyfetch: unstable-2021-06-19 -> 0.2.0`                        |
| [`b952a9b1`](https://github.com/NixOS/nixpkgs/commit/b952a9b16ee8a8b6c45d16d84aa298717624e34f) | `adopt multiple packages` …

chore(flake/nixpkgs): `a77874bb` -> `58371472`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                             |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`b0819012`](https://github.com/NixOS/nixpkgs/commit/b0819012c4d3bcbe68024d6da3576a7e5607606d) | `gh: 2.2.0 -> 2.3.0`                                                       |
| [`ea90c516`](https://github.com/NixOS/nixpkgs/commit/ea90c516e79a9231acef34e369c544836242ef34) | `nixos/shairport-sync: add firewall rules`                                 |
| [`34d4676e`](https://github.com/NixOS/nixpkgs/commit/34d4676e9d9d8778523235e52b9e9c5bd1f8d6d9) …

chore(flake/nixpkgs): `58371472` -> `b0819012`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| [`6bad84a2`](https://github.com/NixOS/nixpkgs/commit/6bad84a25da85dd16a2c9badd2ed893ad231210f) | `shellcheck: drop removeAttrs workaround for hydraPlatforms`                          |
| [`31ea056e`](https://github.com/NixOS/nixpkgs/commit/31ea056e676c29b1f996098165a76ce0bafe1124) | `poke: 1.3 → 1.4`                                                                     |
| …

chore(flake/nixpkgs): `b0819012` -> `bc0e3db2`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                             |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`f9a1652a`](https://github.com/NixOS/nixpkgs/commit/f9a1652a858329525c143450db2474ef439cf6c1) | `python3Packages.heatzypy: init at 1.4.2`                                  |
| [`23f4fb4d`](https://github.com/NixOS/nixpkgs/commit/23f4fb4d14f37fe5772fe5e0f9511b0349e360d7) | `python3Packages.zeversolarlocal: init at 1.1.0`                           |
| [`e1fb73a3`](https://github.com/NixOS/nixpkgs/commit/e1fb73a3f2482869ebf3b36a4e33dbeedccf0331) …

chore(flake/nixpkgs): `bc0e3db2` -> `f9a1652a`

---

protoletariat/fdsetgen.py

I'm using Click 7.1.2. For some reason, the input file paths were `bytes` instead of `str`, causing lots of errors when I tried to run `protol`.
This PR fixed the problem for me. It's probably a safe thing to merge, and it guards against other strange Click incompatibilities.
In case it matters, here's how I was invoking `protol`:
https://github.com/shawwn/tensorflow-checkpoint-reader/blob/c8a77dc82c88f52971f11a96e59d5ace7b595611/build.sh#L15-L16

fix: ensure every path is decoded using os.fsdecode

---

flake.lock

| SHA256                                                                                         | Commit Message                                                              |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`7f6a2d56`](https://github.com/NixOS/nixpkgs/commit/7f6a2d5663d0127d4aa48d2e839fd04aaa1d93e7) | `oci-containers: fix imageFile example`                                     |
| [`deef812a`](https://github.com/NixOS/nixpkgs/commit/deef812ae8b600fd6f70d06eddcb325b79e267dd) | `frama-c: 23.1 (Vanadium) → 24.0 (Chromium)`                                |
| [`652b351d`](https://github.com/NixOS/nixpkgs/commit/652b351d3e03e3bd437a6f0fc0a600abef0ee …

chore(flake/nixpkgs): `f9a1652a` -> `7f6a2d56`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`96e01b7e`](https://github.com/NixOS/nixpkgs/commit/96e01b7e1689d3ee9d2a674a99aa9702e808f5f3) | `gnomeExtensions: fix ddterm`                                                       |
| [`44b84602`](https://github.com/NixOS/nixpkgs/commit/44b84602c940f4693789501f42f05d007c463031) | `python3Packages.myfitnesspal: 1.16.4 -> 1.16.5`                                    |
| …

chore(flake/nixpkgs): `7f6a2d56` -> `11e5bcc9`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                             |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- |
| [`f88b90f5`](https://github.com/NixOS/nixpkgs/commit/f88b90f5c329a5a4d49e142315fbcb27986a13b1) | `facedetect: use Python 3`                                                 |
| [`eec28b8c`](https://github.com/NixOS/nixpkgs/commit/eec28b8cfd7923a876fb47af8a0459c1a550fd97) | `pypy3: 7.3.5 -> 7.3.7 (#147875)`                                          |
| [`a3647046`](https://github.com/NixOS/nixpkgs/commit/a3647046fee002a70a5c121101d46535afd640e0) …

chore(flake/nixpkgs): `11e5bcc9` -> `f88b90f5`

---

flake.lock

| SHA256                                                                                         | Commit Message                                                                  |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`6371e5c3`](https://github.com/NixOS/nixpkgs/commit/6371e5c34c0ccd62016ffaeccc6b420ef3f21b80) | `matrix-synapse-plugins.matrix-synapse-mjolnir-antispam: 1.1.20 -> 1.2.1`       |
| [`7a87a486`](https://github.com/NixOS/nixpkgs/commit/7a87a486424f5ec7b33a38af114e0a61c1b4739e) | `runc: 1.0.2 -> 1.0.3`                                                          |
| [`dec87b9b`](https://github.com/NixOS/nixpkgs/commit/dec87b9b79e716af2a25d …

chore(flake/nixpkgs): `f88b90f5` -> `63628eb0`

---

flake.lock

| SHA256                                                                                                    | Commit Message                                    |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
| [`58ef019d`](https://github.com/nix-community/poetry2nix/commit/58ef019d39aa12b05bba68936b57331a1892dc66) | `overrides: scipy: fix for version >= 1.7.0`      |
| [`3def814c`](https://github.com/nix-community/poetry2nix/commit/3def814c0a31a4edb9dc1333838e02b2efa6fac3) | `overrides: wtforms: add`                         |
| [`64da99c7`](https://github.com/nix-community/poetry2nix/commit/64da99c770026a517521d690ea21010450b1d781) | `overrides: matplotlib: fix for version …

chore(flake/poetry2nix): `41732777` -> `a4b76920`

---

flake.lock

| [`74d8cc01`](https://github.com/NixOS/nixpkgs/commit/74d8cc01903dc3391fafa13be4148985b93c3491) | `evolution-data-server: 3.42.1 -> 3.42.2`                                 |
| [`0a0a8ebc`](https://github.com/NixOS/nixpkgs/commit/0a0a8ebc51906c8c341d50fe5a2a4367e7a83c06) | `python38Packages.soco: 0.24.1 -> 0.25.0`                                 |
| [`7483fa78`](https://github.com/NixOS/nixpkgs/commit/7483fa7825883ffab740d26ee21247e804928ad6) | …

chore(flake/nixpkgs): `63628eb0` -> `f2365edc`

---

protoletariat/rewrite.py
protoletariat/tests/test_rewrite.py

- test: add failing test
- fix: add more underscores for imports
- style: remove unnecessar punctuation
- test: nest packages

fix: handle underscores in package names

---

.github/workflows/ci.yml
flake.nix
poetry.lock
pyproject.toml

- chore: bump nixpkgs
- chore: remove bogus flake input
- chore: remove `useLLVM` usage

chore(deps): drop python 3.7 support; bump nixpkgs deps

---

flake.nix
poetry.lock
pyproject.toml

- chore: bump nixpkgs
- chore: remove bogus flake input
- chore: remove `useLLVM` usage
- fix(deps): support python `protobuf==4`
Closes #571

fix: support pyproto4

---

protoletariat/fdsetgen.py

Previously the entries in the pyi files were just a function of whatever order glob return them in.  This ensures at least some kind of consistent order.

Ensure consistent ordering in generated __init__.pyi files

---

protoletariat/__main__.py
protoletariat/fdsetgen.py
protoletariat/tests/conftest.py

This PR adds support for forwarding unknown arguments to protoc, including `--descriptor_set_in`. Closes #478.

feat(protoc): forward protoc arguments to protoc generator
